/**
 * Models for dotnet format JSON report structure
 * Generated by: dotnet format --report <path> --report-format json
 */

export interface ProjectId {
  Id: string;
}

export interface DocumentId {
  ProjectId: ProjectId;
  Id: string;
}

export interface FileChange {
  LineNumber: number;
  CharNumber: number;
  DiagnosticId: string;
  FormatDescription: string;
}

export interface DotnetFormatDiagnostic {
  DocumentId: DocumentId;
  FileName: string;
  FilePath: string;
  FileChanges: FileChange[];
}

export type DotnetFormatReport = DotnetFormatDiagnostic[];
