/**
 * Models for dotnet format JSON report structure
 * Generated by: dotnet format --report <path> --report-format json
 */

export type DiagnosticCategory = 'style' | 'whitespace' | 'analyzer';

export interface DotnetFormatDiagnostic {
  filePath: string;
  startLine: number;
  startColumn: number;
  endLine?: number;
  endColumn?: number;
  ruleId: string;
  category: DiagnosticCategory;
  message: string;
}

export interface DotnetFormatReport {
  version: string;
  diagnostics: DotnetFormatDiagnostic[];
}
