name: SARIF EXPORTER CI

on:
  pull_request:
    branches: [master]
    types: [opened, reopened]
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - '**'

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

      - name: Version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF_NAME:1}" >> "$GITHUB_ENV"
          git config --global user.email "heni.fazzani@gmail.com"
          git config --global user.name "Heni FAZZANI"

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: 'Version ${{ env.VERSION }}'
          files: |
            ./bin/**/js
      - name: Publish
        run: npm version ${{ env.VERSION }} --git-tag-version=false --allow-same-version && npm publish --provenance --access public
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
